### ISSUE TITLE
How to build project for local development?

### ISSUE THREAD

**Issue by ShiroTohu** [caffeine-addictt/thread#23]
# How to build project for local development?

I understand that this project uses Poetry to manage and handle project dependencies, though I'm unsure how to build the project. I understand there is documentation for installing it manually. These are the steps I went through.

```
pipx install poetry
poetry install
poetry run python src/thread
```

Though when I run the project it return's this error:

```
Traceback (most recent call last):
  File "C:\Users\shirotohu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\shirotohu\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Mine\Programming\thread\src\thread\__main__.py", line 3, in <module>
    from .cli import app
ImportError: attempted relative import with no known parent package
```

 - I am running python version 3.9.2
 - I have looked at sys.path using `poetry run python` and importing sys
   - Only thing to note with this output is `D:\\Mine\\Programming\\thread\\src`
   
### Expected Output
![image](https://github.com/caffeine-addictt/thread/assets/44159210/a2242e73-4e8b-43dc-bc85-45a0e1753830)
If I'm not mistaken, this should be the expected output.

**Comment by ShiroTohu** [comment]
that worked perfectly, thanks very much!
